# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4d8c38e15b51f03d371ff8e1fb9c273c3a81a9bfb11450e07deb126c1859853cce88cc877fa79a1592aaecf75ddc1d47a4669adc95b36fbf3f1a4f8d4cbb53

test:
  secret_key_base: 9b939bbbd2c6f0ea0f051625a6477be885323c35e3c0acc46ce469cb06e4c34afd0c355a8607fd78ad611fb6af358473dabdfbe7ef43700381a9f78ccb399ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
